language: python
sudo: false
python: 
  - 2.7
  - 3.6

install:
  - pip install codecov pytest
  - pip install ./dist/consumer-*.whl
script:
  - python setup.py pytest
deploy:
  - provider: pypi
    user: zeek
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true

after_deploy:
 - codecov