language: python
sudo: false
python: 
  - 2.7
  - 3.6

install:
  - pip install codecov pytest

script:
  - python setup.py pytest
  - codecov

 deploy:
  - provider: pypi
    user: zeek
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
